### ISSUE TITLE
Utilities traces should not appear in stdout

### ISSUE THREAD

**Issue by yurug** [colis-anr/colis-language#103]
The debugging traces of utilities are printed in the stdout of the interpreter. This changes the semantics of the script and this is therefore unsound.

We could extend the state of the interpreter with a log to put such debugging information, right?

**Comment by benozol** [comment]
Yes indeed: they are only on stdout because I didn’t really know in a rush someplace else to print them.

It could be, as you suggest, just another output stream like stdout. We would, however, lose the interleaving between normal stdout and debug information, which might be useful to understand what a script did. Should the second stream contain stdout and debug lines? Either would be easy to implement.

**Comment by Niols** [comment]
Indeed, it would be nice to also have stdout in that debug stream !
